from __future__ import annotations

import asyncio
import dataclasses
import hashlib
import json
import os
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, AsyncIterator, Callable

from .base import AgentProviderCapabilities, JsonDict, ProviderEnvelope


_AUTO_ALLOW_TOOLS = (
    "Read",
    "Glob",
    "Grep",
    "LS",
    "TodoRead",
)
_EDIT_TOOLS = {"Write", "Edit", "MultiEdit", "NotebookEdit"}
_BASH_TOOL = "Bash"
_TRANSCRIPT_SCAN_LIMIT = 200
_SESSION_SYNC_LIMIT = 200
# Claude Code stores local slash-command caveats/stdout as user-role
# transcript records. They are control metadata, not chat history.
_LOCAL_COMMAND_TAG_PREFIXES = (
    "<local-command-caveat",
    "<local-command-stdout",
    "<command-name",
    "<command-message",
    "<command-args",
    "caveat: the messages below were generated by the user while running local commands",
)


class ClaudeAgentSdkRuntimeMissing(RuntimeError):
    pass


def _string(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value)
    return text if text else None


def _payload_value(request: JsonDict, key: str) -> Any:
    if key in request:
        return request.get(key)
    payload = request.get("payload")
    if isinstance(payload, dict):
        return payload.get(key)
    return None


def _jsonable(value: Any) -> Any:
    if dataclasses.is_dataclass(value):
        return _jsonable(dataclasses.asdict(value))
    if isinstance(value, dict):
        return {str(k): _jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_jsonable(item) for item in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if hasattr(value, "__dict__"):
        return {
            str(k): _jsonable(v)
            for k, v in vars(value).items()
            if not str(k).startswith("_")
        }
    return str(value)


def _fingerprint(tool_name: str, input_data: JsonDict) -> str:
    try:
        body = json.dumps(input_data, sort_keys=True, separators=(",", ":"))
    except TypeError:
        body = json.dumps(_jsonable(input_data), sort_keys=True, separators=(",", ":"))
    digest = hashlib.sha256(f"{tool_name}\n{body}".encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def _approval_decision_allows(response: JsonDict | None) -> bool:
    if not isinstance(response, dict):
        return False
    decision = str(response.get("decision") or response.get("status") or "").lower()
    if decision in {"approved", "approve", "allow", "allowed", "yes"}:
        return True
    app_server_decision = response.get("app_server_decision")
    if isinstance(app_server_decision, dict):
        decision = str(
            app_server_decision.get("decision")
            or app_server_decision.get("status")
            or app_server_decision.get("behavior")
            or ""
        ).lower()
        return decision in {"approved", "approve", "allow", "allowed", "yes"}
    return False


def _timestamp_seconds(value: Any) -> int | None:
    if isinstance(value, (int, float)):
        number = float(value)
        if number > 10_000_000_000:
            number = number / 1000
        return int(number)
    if isinstance(value, str) and value:
        text = value.strip()
        if text.endswith("Z"):
            text = f"{text[:-1]}+00:00"
        try:
            return int(datetime.fromisoformat(text).timestamp())
        except ValueError:
            return None
    return None


def _clean_transcript_text(value: Any) -> str | None:
    text = _string(value)
    if not text:
        return None
    stripped = text.strip()
    lowered = stripped.lower()
    if any(lowered.startswith(prefix) for prefix in _LOCAL_COMMAND_TAG_PREFIXES):
        return None
    return stripped or None


def _is_auth_required_text(value: str | None) -> bool:
    if not value:
        return False
    lowered = value.strip().lower()
    return "not logged in" in lowered and "/login" in lowered


def _encoded_claude_cwd(cwd: str) -> str:
    path = str(Path(cwd or ".").expanduser().resolve())
    return "".join(char if char.isalnum() else "-" for char in path)


def _transcript_search_roots(cwd: str, *, all_projects: bool = False) -> list[Path]:
    roots: list[Path] = []
    env_paths = [
        os.environ.get("BOTSDOCK_CLAUDE_TRANSCRIPT_FILE"),
        os.environ.get("CLAUDE_CODE_TRANSCRIPT_FILE"),
    ]
    env_dirs = [
        os.environ.get("BOTSDOCK_CLAUDE_TRANSCRIPT_DIR"),
        os.environ.get("CLAUDE_CODE_TRANSCRIPT_DIR"),
    ]
    for value in env_paths:
        if value:
            roots.append(Path(value).expanduser())
    for value in env_dirs:
        if value:
            roots.extend(Path(part).expanduser() for part in value.split(os.pathsep) if part)
    home_projects = Path.home() / ".claude" / "projects"
    roots.append(home_projects if all_projects else home_projects / _encoded_claude_cwd(cwd))
    return roots


def _candidate_transcript_files(
    cwd: str,
    *,
    limit: int = _TRANSCRIPT_SCAN_LIMIT,
    all_projects: bool = False,
) -> list[Path]:
    files: list[Path] = []
    seen: set[str] = set()
    home_projects = Path.home() / ".claude" / "projects"
    for root in _transcript_search_roots(cwd, all_projects=all_projects):
        try:
            if root.is_file() and root.suffix == ".jsonl":
                candidates = [root]
            elif root.is_dir():
                if all_projects and root == home_projects:
                    candidates = list(root.glob("*/*.jsonl"))
                else:
                    candidates = list(root.glob("*.jsonl"))
            else:
                candidates = []
        except OSError:
            candidates = []
        for candidate in candidates:
            try:
                resolved = str(candidate.resolve())
            except OSError:
                resolved = str(candidate)
            if resolved in seen or candidate.name.startswith("."):
                continue
            seen.add(resolved)
            files.append(candidate)
    files.sort(key=lambda path: _path_mtime(path), reverse=True)
    return files[:limit]


def _path_mtime(path: Path) -> int:
    try:
        return int(path.stat().st_mtime)
    except OSError:
        return 0


def _load_jsonl(path: Path) -> list[JsonDict]:
    records: list[JsonDict] = []
    try:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                try:
                    value = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if isinstance(value, dict):
                    records.append(value)
    except OSError:
        return []
    return records


def _record_session_id(record: JsonDict) -> str | None:
    message = record.get("message") if isinstance(record.get("message"), dict) else {}
    for key in ("session_id", "sessionId", "sessionID", "conversation_id", "conversationId"):
        value = record.get(key) or message.get(key)
        text = _string(value)
        if text:
            return text
    return None


def _record_cwd(record: JsonDict) -> str | None:
    message = record.get("message") if isinstance(record.get("message"), dict) else {}
    return _string(record.get("cwd") or message.get("cwd"))


def _records_cwd(records: list[JsonDict]) -> str | None:
    for record in records:
        cwd = _record_cwd(record)
        if cwd:
            return cwd
    return None


def _find_transcript_file(
    cwd: str,
    session_id: str | None,
    *,
    all_projects: bool = False,
) -> Path | None:
    if not session_id:
        return None
    candidates = _candidate_transcript_files(cwd, all_projects=all_projects)
    for path in candidates:
        if path.stem == session_id or session_id in path.name:
            return path
    for path in candidates:
        for record in _load_jsonl(path)[:20]:
            if _record_session_id(record) == session_id:
                return path
    return None


def _record_role(record: JsonDict) -> str | None:
    message = record.get("message") if isinstance(record.get("message"), dict) else {}
    for role in (record.get("role"), message.get("role"), record.get("type")):
        if role in {"user", "assistant"}:
            return str(role)
    return None


def _record_uuid(record: JsonDict, index: int) -> str:
    message = record.get("message") if isinstance(record.get("message"), dict) else {}
    return (
        _string(record.get("uuid"))
        or _string(record.get("id"))
        or _string(message.get("id"))
        or f"item-{index}"
    )


def _message_content(record: JsonDict) -> Any:
    message = record.get("message")
    if isinstance(message, dict) and "content" in message:
        return message.get("content")
    if "content" in record:
        return record.get("content")
    return message


def _content_blocks(content: Any) -> list[Any]:
    if isinstance(content, list):
        return content
    return [content] if content is not None else []


def _extract_content_text(content: Any, *, include_tool_results: bool = False) -> str | None:
    parts: list[str] = []
    for block in _content_blocks(content):
        if isinstance(block, str):
            text = _clean_transcript_text(block)
            if text:
                parts.append(text)
            continue
        if not isinstance(block, dict):
            continue
        block_type = block.get("type")
        if block_type == "text":
            text = block.get("text")
        elif block_type == "thinking":
            text = block.get("thinking")
        elif block_type == "tool_result" and include_tool_results:
            text = block.get("content")
        elif block_type is None:
            text = block.get("text") or block.get("content")
        else:
            text = None
        if isinstance(text, list):
            nested = _extract_content_text(text, include_tool_results=True)
            if nested:
                parts.append(nested)
        elif text:
            cleaned = _clean_transcript_text(text)
            if cleaned:
                parts.append(cleaned)
    text = "\n".join(part for part in parts if part).strip()
    return text or None


def _content_has_user_text(content: Any) -> bool:
    return _extract_content_text(content) is not None


def _apply_tool_results_to_pending(content: Any, pending: dict[str, JsonDict]) -> None:
    for block in _content_blocks(content):
        if not isinstance(block, dict) or block.get("type") != "tool_result":
            continue
        tool_use_id = _string(block.get("tool_use_id") or block.get("toolUseId"))
        if not tool_use_id or tool_use_id not in pending:
            continue
        item = pending[tool_use_id]
        output = _extract_content_text(block.get("content"), include_tool_results=True)
        item["aggregatedOutput"] = output or ""
        item["status"] = "failed" if block.get("is_error") or block.get("isError") else "completed"


def _assistant_items_from_content(content: Any, *, base_id: str) -> list[JsonDict]:
    items: list[JsonDict] = []
    text_parts: list[str] = []
    for block_index, block in enumerate(_content_blocks(content)):
        if isinstance(block, str):
            text = _clean_transcript_text(block)
            if text:
                text_parts.append(text)
            continue
        if not isinstance(block, dict):
            continue
        block_type = block.get("type")
        if block_type == "text":
            text = _clean_transcript_text(block.get("text"))
            if text:
                text_parts.append(text)
        elif block_type == "thinking":
            text = _clean_transcript_text(block.get("thinking"))
            if text:
                items.append(
                    {
                        "id": _string(block.get("id")) or f"{base_id}:thinking:{block_index}",
                        "type": "reasoning",
                        "text": text,
                    }
                )
        elif block_type == "tool_use":
            name = _string(block.get("name")) or "tool"
            input_data = block.get("input") if isinstance(block.get("input"), dict) else {}
            if name == _BASH_TOOL:
                command = _string(input_data.get("command")) or name
                items.append(
                    {
                        "id": _string(block.get("id")) or f"{base_id}:tool:{block_index}",
                        "type": "commandExecution",
                        "command": command,
                        "aggregatedOutput": "",
                        "status": "completed",
                    }
                )
    if text_parts:
        items.insert(
            0,
            {
                "id": f"{base_id}:assistant",
                "type": "agentMessage",
                "phase": "final_answer",
                "text": "\n".join(text_parts).strip(),
            },
        )
    return [item for item in items if item.get("text") or item.get("command")]


def _messages_to_history_turns(
    *,
    session_id: str,
    messages: list[JsonDict],
) -> list[JsonDict]:
    turns: list[JsonDict] = []
    current: JsonDict | None = None
    pending_commands: dict[str, JsonDict] = {}

    def start_turn(record: JsonDict, index: int, text: str | None = None) -> JsonDict:
        item_id = _record_uuid(record, index)
        started_at = _timestamp_seconds(record.get("timestamp"))
        turn = {
            "id": f"claude-{session_id}-{item_id}"[:128],
            "status": "completed",
            "source": "claude_code_transcript",
            "startedAt": started_at,
            "completedAt": started_at,
            "items": [],
        }
        if text:
            turn["items"].append(
                {
                    "id": f"{item_id}:user",
                    "type": "userMessage",
                    "content": text,
                }
            )
        turns.append(turn)
        return turn

    for index, record in enumerate(messages):
        role = _record_role(record)
        if role is None:
            continue
        content = _message_content(record)
        item_id = _record_uuid(record, index)
        timestamp = _timestamp_seconds(record.get("timestamp"))
        if role == "user":
            _apply_tool_results_to_pending(content, pending_commands)
            if not _content_has_user_text(content):
                continue
            text = _extract_content_text(content)
            if not text:
                continue
            current = start_turn(record, index, text)
        elif role == "assistant":
            if current is None:
                current = start_turn(record, index)
            for item in _assistant_items_from_content(content, base_id=item_id):
                current["items"].append(item)
                if item.get("type") == "commandExecution":
                    pending_commands[str(item["id"])] = item
            if timestamp:
                current["completedAt"] = timestamp
    return [
        turn
        for turn in turns
        if turn.get("items")
        and any(
            isinstance(item, dict) and item.get("type") == "userMessage"
            for item in turn.get("items", [])
        )
    ]


def _first_user_message_from_turns(turns: list[JsonDict]) -> str | None:
    for turn in turns:
        for item in turn.get("items", []):
            if isinstance(item, dict) and item.get("type") == "userMessage":
                return _clean_transcript_text(item.get("content"))
    return None


def _page_turns(turns: list[JsonDict], *, limit: int, cursor: Any) -> tuple[list[JsonDict], str | None]:
    limit = max(1, min(int(limit or 20), 50))
    total = len(turns)
    if cursor is None:
        start = max(0, total - limit)
        page = turns[start:total]
    else:
        try:
            end = max(0, min(total, int(str(cursor))))
        except ValueError:
            end = total
        start = max(0, end - limit)
        page = turns[start:end]
    return page, (str(start) if start > 0 else None)


class ClaudeAgentSdkProvider:
    name = "claude_code"
    capabilities = AgentProviderCapabilities(
        can_resume_session=True,
        can_cancel_turn=True,
        can_request_approval=True,
        can_report_file_activity=True,
        event_types=(
            "assistant.message",
            "tool.started",
            "tool.completed",
            "file.changed",
            "approval.requested",
            "approval.resolved",
            "reasoning.delta",
            "command.started",
            "command.output",
            "command.completed",
            "provider.warning",
            "provider.debug",
            "turn.completed",
            "turn.failed",
            "turn.cancelled",
        ),
    )

    def __init__(
        self,
        *,
        cwd: str,
        default_cwd: str | None = None,
        exclude_history_cwds: list[str] | tuple[str, ...] = (),
        model: str | None = None,
        cli_path: str | None = None,
        approval_timeout_seconds: float = 900,
    ) -> None:
        self.cwd = cwd
        self.default_cwd = default_cwd
        self._history_excluded_cwds = {
            str(Path(item).expanduser().resolve())
            for item in exclude_history_cwds
            if item
        }
        self.model = model
        self.cli_path = cli_path
        self.approval_timeout_seconds = approval_timeout_seconds
        self._sdk: Any | None = None
        self._sdk_types: Any | None = None
        self._active_clients: dict[str, Any] = {}
        self._cancel_events: dict[str, asyncio.Event] = {}
        self._pending_approvals: dict[str, asyncio.Future[JsonDict]] = {}

    async def start(self) -> None:
        # The SDK import is intentionally lazy so Codex-only deployments do not
        # need Claude dependencies installed.
        try:
            import claude_agent_sdk  # type: ignore
            import claude_agent_sdk.types as claude_agent_sdk_types  # type: ignore
        except ImportError as err:
            raise ClaudeAgentSdkRuntimeMissing(
                "claude_agent_sdk is not installed. Install the optional "
                "claude dependency with `pip install claude-agent-sdk`."
            ) from err
        self._sdk = claude_agent_sdk
        self._sdk_types = claude_agent_sdk_types

    async def stop(self) -> None:
        for client in list(self._active_clients.values()):
            disconnect = getattr(client, "disconnect", None)
            if callable(disconnect):
                try:
                    await disconnect()
                except Exception:
                    pass
        self._active_clients.clear()
        self._cancel_events.clear()
        self._sdk = None
        self._sdk_types = None

    def thread_sync_report(self, *, limit: int = _SESSION_SYNC_LIMIT) -> JsonDict:
        threads = self._list_history_threads(limit=limit)
        return {
            "type": "thread.sync",
            "provider": self.name,
            "threads": threads,
            "workspaces": self._workspaces_from_threads(threads),
            "authoritative": bool(threads),
        }

    def read_thread_history(self, request: JsonDict) -> JsonDict:
        session_id = (
            _string(_payload_value(request, "provider_session_id"))
            or _string(_payload_value(request, "provider_thread_id"))
            or _string(_payload_value(request, "app_server_thread_id"))
        )
        limit = int(_payload_value(request, "limit") or 20)
        cursor = _payload_value(request, "cursor")
        turns = self._load_history_turns(session_id=session_id)
        page, next_cursor = _page_turns(turns, limit=limit, cursor=cursor)
        return {
            "type": "thread.history",
            "provider": self.name,
            "thread_id": _payload_value(request, "thread_id"),
            "provider_session_id": session_id,
            "turns": page,
            "has_more_before": bool(next_cursor),
            "next_cursor": next_cursor,
            "direction": _payload_value(request, "direction") or "latest",
        }

    def _sdk_module(self) -> Any | None:
        if self._sdk is not None:
            return self._sdk
        try:
            import claude_agent_sdk  # type: ignore
        except ImportError:
            return None
        return claude_agent_sdk

    def _list_history_threads(self, *, limit: int) -> list[JsonDict]:
        # Prefer the official SDK session index when available. The JSONL
        # scanner below is intentionally isolated as a compatibility adapter
        # for older SDKs or environments where the SDK cannot enumerate sessions.
        threads = self._list_threads_from_sdk(limit=limit)
        if threads:
            return threads
        return self._list_threads_from_transcripts(limit=limit)

    def _list_threads_from_sdk(self, *, limit: int) -> list[JsonDict]:
        sdk = self._sdk_module()
        list_sessions = getattr(sdk, "list_sessions", None) if sdk is not None else None
        if not callable(list_sessions):
            return []
        try:
            sessions = list_sessions(
                directory=None,
                limit=limit,
                include_worktrees=True,
            )
        except TypeError:
            try:
                sessions = list_sessions(directory=None, limit=limit)
            except Exception:
                return []
        except Exception:
            return []
        threads: list[JsonDict] = []
        for session in sessions or []:
            session_info = _jsonable(session)
            session_id = _string(
                session_info.get("session_id")
                or session_info.get("sessionId")
                or session_info.get("id")
            )
            if not session_id:
                continue
            messages = self._load_messages_from_sdk(session_id)
            if not messages:
                messages = self._load_messages_from_transcript(session_id)
            turns = _messages_to_history_turns(session_id=session_id, messages=messages)
            if not turns:
                continue
            thread = self._thread_from_session_info(
                session_info,
                first_user_text=_first_user_message_from_turns(turns),
                cwd=_records_cwd(messages),
            )
            if thread is not None:
                threads.append(thread)
        return threads

    def _list_threads_from_transcripts(self, *, limit: int) -> list[JsonDict]:
        threads: list[JsonDict] = []
        for path in _candidate_transcript_files(
            self.cwd,
            limit=limit,
            all_projects=True,
        ):
            records = _load_jsonl(path)
            if not records:
                continue
            session_id = (
                _record_session_id(records[0])
                or next((_record_session_id(record) for record in records if _record_session_id(record)), None)
                or path.stem
            )
            turns = _messages_to_history_turns(session_id=session_id, messages=records)
            if not turns:
                continue
            first_user = _first_user_message_from_turns(turns)
            cwd = _records_cwd(records)
            if not cwd:
                continue
            created_at = next(
                (
                    _timestamp_seconds(record.get("timestamp"))
                    for record in records
                    if _timestamp_seconds(record.get("timestamp")) is not None
                ),
                None,
            )
            thread = self._history_thread(
                session_id=session_id,
                title=first_user or f"Claude session {session_id[:8]}",
                preview=first_user,
                cwd=cwd,
                created_at=created_at,
                updated_at=_path_mtime(path),
            )
            if thread is not None:
                threads.append(thread)
        return threads

    def _thread_from_session_info(
        self,
        info: JsonDict,
        *,
        first_user_text: str | None = None,
        cwd: str | None = None,
    ) -> JsonDict | None:
        session_id = _string(
            info.get("session_id") or info.get("sessionId") or info.get("id")
        )
        if not session_id:
            return None
        title = _string(
            info.get("summary")
            or info.get("custom_title")
            or info.get("customTitle")
            or info.get("first_prompt")
            or info.get("firstPrompt")
        )
        title = _clean_transcript_text(title)
        preview = _clean_transcript_text(info.get("first_prompt") or info.get("firstPrompt"))
        if title and title.lstrip().startswith("/") and first_user_text:
            title = first_user_text
        if preview and preview.lstrip().startswith("/") and first_user_text:
            preview = first_user_text
        cwd = _string(info.get("cwd")) or cwd
        if not cwd:
            return None
        return self._history_thread(
            session_id=session_id,
            title=title or f"Claude session {session_id[:8]}",
            preview=preview,
            cwd=cwd,
            created_at=_timestamp_seconds(info.get("created_at") or info.get("createdAt")),
            updated_at=_timestamp_seconds(info.get("last_modified") or info.get("updatedAt")),
            current_branch=_string(info.get("git_branch") or info.get("gitBranch")),
        )

    def _history_thread(
        self,
        *,
        session_id: str,
        title: str,
        preview: str | None,
        cwd: str,
        created_at: int | None,
        updated_at: int | None,
        current_branch: str | None = None,
    ) -> JsonDict | None:
        path = str(Path(cwd).expanduser().resolve())
        if path in self._history_excluded_cwds:
            return None
        return {
            "id": session_id,
            "app_server_thread_id": session_id,
            "provider_thread_id": session_id,
            "provider_session_id": session_id,
            "title": title[:255],
            "preview": preview[:255] if preview else None,
            "status": "idle",
            "remote_path": path,
            "workspace_name": Path(path).name or path,
            "current_branch": current_branch,
            "created_at": created_at,
            "updated_at": updated_at,
        }

    def _workspaces_from_threads(self, threads: list[JsonDict]) -> list[JsonDict]:
        workspaces: list[JsonDict] = []
        seen: set[str] = set()
        for thread in threads:
            remote_path = _string(thread.get("remote_path"))
            if not remote_path or remote_path in seen:
                continue
            seen.add(remote_path)
            workspaces.append(
                {
                    "name": thread.get("workspace_name") or Path(remote_path).name or remote_path,
                    "path": remote_path,
                    "remote_path": remote_path,
                    "current_branch": thread.get("current_branch"),
                }
            )
        return workspaces

    def _load_history_turns(self, *, session_id: str | None) -> list[JsonDict]:
        if not session_id:
            return []
        messages = self._load_messages_from_sdk(session_id)
        if not messages:
            messages = self._load_messages_from_transcript(session_id)
        return _messages_to_history_turns(session_id=session_id, messages=messages)

    def _load_messages_from_sdk(self, session_id: str) -> list[JsonDict]:
        sdk = self._sdk_module()
        get_messages = getattr(sdk, "get_session_messages", None) if sdk is not None else None
        if not callable(get_messages):
            return []
        try:
            messages = get_messages(session_id, directory=None)
        except TypeError:
            try:
                messages = get_messages(session_id)
            except Exception:
                return []
        except Exception:
            return []
        normalized: list[JsonDict] = []
        for message in messages or []:
            data = _jsonable(message)
            if "message" not in data and "content" in data:
                data = {
                    "type": data.get("type") or data.get("role"),
                    "uuid": data.get("uuid") or data.get("id"),
                    "session_id": data.get("session_id") or session_id,
                    "message": {"content": data.get("content")},
                }
            normalized.append(data)
        return normalized

    def _load_messages_from_transcript(self, session_id: str) -> list[JsonDict]:
        path = _find_transcript_file(self.cwd, session_id, all_projects=True)
        if path is None:
            return []
        return _load_jsonl(path)

    async def start_turn(self, request: JsonDict) -> AsyncIterator[ProviderEnvelope]:
        if self._sdk is None:
            try:
                await self.start()
            except Exception as err:
                yield self._turn_failed(
                    request,
                    code=self._error_code(err),
                    message=str(err) or type(err).__name__,
                    raw_event={"error_type": type(err).__name__},
                )
                return
        assert self._sdk is not None
        assert self._sdk_types is not None

        prompt = _string(_payload_value(request, "prompt"))
        if not prompt:
            yield self._turn_failed(
                request,
                code="invalid_request",
                message="prompt is required",
            )
            return

        turn_id = _string(_payload_value(request, "turn_id")) or uuid.uuid4().hex
        cancel_event = asyncio.Event()
        self._cancel_events[turn_id] = cancel_event
        queue: asyncio.Queue[ProviderEnvelope | None] = asyncio.Queue()
        try:
            cwd = self._cwd_for_request(request)
        except ValueError as err:
            yield self._turn_failed(
                request,
                code="invalid_request",
                message=str(err),
            )
            return
        options = self._build_options(
            request,
            cwd=cwd,
            can_use_tool=self._build_permission_handler(request, queue),
        )

        yield self._envelope(
            "turn.started",
            request,
            {
                "provider": self.name,
                "cwd": str(cwd),
            },
        )

        async def run_sdk() -> None:
            client = None
            try:
                client = self._sdk.ClaudeSDKClient(options=options)
                self._active_clients[turn_id] = client
                async with client:
                    await client.query(prompt)
                    async for message in client.receive_response():
                        if cancel_event.is_set():
                            break
                        for envelope in self.map_message(request, message):
                            await queue.put(envelope)
                if cancel_event.is_set():
                    await queue.put(
                        self._envelope(
                            "turn.cancelled",
                            request,
                            {"status": "cancelled", "provider": self.name},
                        )
                    )
            except Exception as err:
                await queue.put(
                    self._turn_failed(
                        request,
                        code=self._error_code(err),
                        message=str(err) or type(err).__name__,
                        raw_event={"error_type": type(err).__name__},
                    )
                )
            finally:
                if client is not None:
                    self._active_clients.pop(turn_id, None)
                self._cancel_events.pop(turn_id, None)
                await queue.put(None)

        task = asyncio.create_task(run_sdk())
        try:
            while True:
                item = await queue.get()
                if item is None:
                    break
                yield item
            await task
        finally:
            if not task.done():
                task.cancel()
                try:
                    await task
                except asyncio.CancelledError:
                    pass

    async def cancel_turn(self, request: JsonDict) -> ProviderEnvelope:
        turn_id = _string(_payload_value(request, "turn_id"))
        if not turn_id:
            return self._turn_failed(
                request,
                code="invalid_request",
                message="turn_id is required for cancellation",
            )
        cancel_event = self._cancel_events.get(turn_id)
        if cancel_event is not None:
            cancel_event.set()
        client = self._active_clients.get(turn_id)
        interrupt = getattr(client, "interrupt", None)
        if callable(interrupt):
            try:
                await interrupt()
            except Exception:
                pass
        return self._envelope(
            "turn.cancelled",
            request,
            {"status": "cancelled", "provider": self.name},
        )

    async def resolve_approval(self, request: JsonDict) -> ProviderEnvelope:
        app_server_request_id = (
            _string(_payload_value(request, "app_server_request_id"))
            or _string(_payload_value(request, "request_id"))
            or _string(_payload_value(request, "provider_request_id"))
        )
        if app_server_request_id:
            future = self._pending_approvals.get(app_server_request_id)
            if future is not None and not future.done():
                future.set_result(dict(request.get("payload") or request))
        return self._envelope(
            "approval.resolved",
            request,
            {
                "provider": self.name,
                "request_id": app_server_request_id,
                "app_server_request_id": app_server_request_id,
                "provider_request_id": app_server_request_id,
                "decision": _payload_value(request, "decision"),
                "request_fingerprint": _payload_value(request, "request_fingerprint"),
            },
        )

    def map_message(self, request: JsonDict, message: Any) -> list[ProviderEnvelope]:
        message_type = type(message).__name__
        raw = _jsonable(message)
        if message_type == "AssistantMessage":
            return self._map_assistant_message(request, message, raw)
        if message_type == "ResultMessage":
            return [self._map_result_message(request, message, raw)]
        if message_type == "StreamEvent":
            envelope = self._map_stream_event(request, message, raw)
            return [envelope] if envelope is not None else []
        if message_type == "RateLimitEvent":
            return [
                self._envelope(
                    "provider.warning",
                    request,
                    {
                        "provider": self.name,
                        "kind": "rate_limit",
                        "rate_limit": raw.get("rate_limit_info", raw),
                    },
                    raw_event=raw,
                    provider_event_id=_string(raw.get("uuid")),
                    provider_session_id=_string(raw.get("session_id")),
                )
            ]
        return []

    def _build_options(
        self,
        request: JsonDict,
        *,
        cwd: Path,
        can_use_tool: Callable[[str, JsonDict, Any], Any] | None,
    ) -> Any:
        assert self._sdk is not None
        model = _string(_payload_value(request, "model")) or self.model
        reasoning_effort = _string(_payload_value(request, "reasoning_effort"))
        provider_session_id = _string(_payload_value(request, "provider_session_id"))
        approval_policy = _string(_payload_value(request, "approval_policy"))
        permission_mode = "dontAsk" if approval_policy == "never" else "default"
        kwargs: JsonDict = {
            "cwd": str(cwd),
            "system_prompt": {"type": "preset", "preset": "claude_code"},
            "tools": {"type": "preset", "preset": "claude_code"},
            "allowed_tools": list(_AUTO_ALLOW_TOOLS),
            "permission_mode": permission_mode,
            "setting_sources": ["user", "project", "local"],
            "env": self._claude_env_overrides(),
            "can_use_tool": None if permission_mode == "dontAsk" else can_use_tool,
        }
        if self.cli_path:
            kwargs["cli_path"] = self.cli_path
        if model:
            kwargs["model"] = model
        if provider_session_id:
            kwargs["resume"] = provider_session_id
        if reasoning_effort in {"low", "medium", "high", "max"}:
            kwargs["effort"] = reasoning_effort
        return self._sdk.ClaudeAgentOptions(**kwargs)

    def _claude_env_overrides(self) -> dict[str, str]:
        env = {"CLAUDE_AGENT_SDK_CLIENT_APP": "botsdock-agent-connector"}
        for key, value in os.environ.items():
            if key.startswith(("ANTHROPIC_", "CLAUDE_CODE_")):
                env[key] = value
        return env

    def _build_permission_handler(
        self,
        request: JsonDict,
        queue: asyncio.Queue[ProviderEnvelope | None],
    ) -> Callable[[str, JsonDict, Any], Any]:
        async def can_use_tool(tool_name: str, input_data: JsonDict, context: Any) -> Any:
            assert self._sdk_types is not None
            if tool_name in _AUTO_ALLOW_TOOLS:
                return self._sdk_types.PermissionResultAllow()

            provider_request_id = f"claude-perm-{uuid.uuid4().hex}"
            request_fingerprint = _fingerprint(tool_name, input_data)
            future = asyncio.get_running_loop().create_future()
            self._pending_approvals[provider_request_id] = future
            payload = {
                "provider": self.name,
                "request_id": provider_request_id,
                "app_server_request_id": provider_request_id,
                "provider_request_id": provider_request_id,
                "request_fingerprint": request_fingerprint,
                "title": f"Claude Code wants to use {tool_name}",
                "kind": "tool",
                "tool_name": tool_name,
                "input": _jsonable(input_data),
                "tool_permission_context": _jsonable(context),
            }
            command = input_data.get("command") if isinstance(input_data, dict) else None
            if isinstance(command, str) and command:
                payload["command"] = command
                payload["kind"] = "command"
            await queue.put(self._envelope("approval.requested", request, payload))
            try:
                response = await asyncio.wait_for(
                    future,
                    timeout=self.approval_timeout_seconds,
                )
            except asyncio.TimeoutError:
                return self._sdk_types.PermissionResultDeny(
                    message="Approval request timed out",
                    interrupt=True,
                )
            finally:
                self._pending_approvals.pop(provider_request_id, None)

            if _approval_decision_allows(response):
                return self._sdk_types.PermissionResultAllow()
            return self._sdk_types.PermissionResultDeny(
                message=_string(response.get("message")) or "Denied by user",
                interrupt=True,
            )

        return can_use_tool

    def _map_assistant_message(
        self,
        request: JsonDict,
        message: Any,
        raw: JsonDict,
    ) -> list[ProviderEnvelope]:
        envelopes: list[ProviderEnvelope] = []
        content = getattr(message, "content", None)
        if not isinstance(content, list):
            return envelopes
        message_id = _string(getattr(message, "message_id", None))
        model = _string(getattr(message, "model", None))
        for block in content:
            block_type = type(block).__name__
            provider_event_id = _string(getattr(block, "id", None)) or message_id
            if block_type == "TextBlock":
                text = _string(getattr(block, "text", None))
                if _is_auth_required_text(text):
                    continue
                if text:
                    envelopes.append(
                        self._envelope(
                            "assistant.message",
                            request,
                            {
                                "role": "assistant",
                                "phase": "final_answer",
                                "text": text,
                                "provider": self.name,
                                "model": model,
                                "provider_message_id": message_id,
                            },
                            raw_event=raw,
                            provider_event_id=provider_event_id,
                        )
                    )
            elif block_type == "ThinkingBlock":
                thinking = _string(getattr(block, "thinking", None))
                if thinking:
                    envelopes.append(
                        self._envelope(
                            "reasoning.delta",
                            request,
                            {
                                "text": thinking,
                                "provider": self.name,
                                "provider_message_id": message_id,
                            },
                            raw_event=raw,
                            provider_event_id=provider_event_id,
                        )
                    )
            elif block_type == "ToolUseBlock":
                envelopes.extend(
                    self._map_tool_use(request, block, raw, provider_event_id)
                )
            elif block_type == "ToolResultBlock":
                envelopes.extend(self._map_tool_result(request, block, raw))
        return envelopes

    def _map_tool_use(
        self,
        request: JsonDict,
        block: Any,
        raw: JsonDict,
        provider_event_id: str | None,
    ) -> list[ProviderEnvelope]:
        tool_name = _string(getattr(block, "name", None)) or "tool"
        item_id = _string(getattr(block, "id", None)) or provider_event_id
        input_data = getattr(block, "input", None)
        input_payload = input_data if isinstance(input_data, dict) else {}
        if tool_name == _BASH_TOOL:
            command = _string(input_payload.get("command")) or tool_name
            return [
                self._envelope(
                    "command.started",
                    request,
                    {
                        "item_id": item_id,
                        "command": command,
                        "status": "running",
                        "provider": self.name,
                        "tool_name": tool_name,
                        "input": _jsonable(input_payload),
                    },
                    raw_event=raw,
                    provider_event_id=provider_event_id,
                )
            ]
        if tool_name in _EDIT_TOOLS:
            path = _string(
                input_payload.get("file_path")
                or input_payload.get("path")
                or input_payload.get("notebook_path")
            )
            return [
                self._envelope(
                    "file.changed",
                    request,
                    {
                        "item_id": item_id,
                        "path": path,
                        "change_type": tool_name.lower(),
                        "status": "started",
                        "provider": self.name,
                        "tool_name": tool_name,
                        "input": _jsonable(input_payload),
                    },
                    raw_event=raw,
                    provider_event_id=provider_event_id,
                )
            ]
        return [
            self._envelope(
                "provider.debug",
                request,
                {
                    "provider": self.name,
                    "kind": "tool_use",
                    "tool_name": tool_name,
                    "item_id": item_id,
                    "input": _jsonable(input_payload),
                },
                raw_event=raw,
                provider_event_id=provider_event_id,
            )
        ]

    def _map_tool_result(
        self,
        request: JsonDict,
        block: Any,
        raw: JsonDict,
    ) -> list[ProviderEnvelope]:
        tool_use_id = _string(getattr(block, "tool_use_id", None))
        content = getattr(block, "content", None)
        text = content if isinstance(content, str) else json.dumps(_jsonable(content))
        is_error = bool(getattr(block, "is_error", False))
        return [
            self._envelope(
                "command.output",
                request,
                {
                    "item_id": tool_use_id,
                    "text": text or "",
                    "status": "failed" if is_error else "completed",
                    "provider": self.name,
                },
                raw_event=raw,
                provider_event_id=tool_use_id,
            ),
            self._envelope(
                "command.completed",
                request,
                {
                    "item_id": tool_use_id,
                    "status": "failed" if is_error else "completed",
                    "provider": self.name,
                },
                raw_event=raw,
                provider_event_id=tool_use_id,
            ),
        ]

    def _map_result_message(
        self,
        request: JsonDict,
        message: Any,
        raw: JsonDict,
    ) -> ProviderEnvelope:
        session_id = _string(getattr(message, "session_id", None))
        turn_id = _string(_payload_value(request, "turn_id"))
        cancelled = bool(turn_id and self._cancel_events.get(turn_id, asyncio.Event()).is_set())
        is_error = bool(getattr(message, "is_error", False))
        event_type = "turn.cancelled" if cancelled else ("turn.failed" if is_error else "turn.completed")
        payload = {
            "provider": self.name,
            "status": "cancelled" if cancelled else ("failed" if is_error else "completed"),
            "provider_session_id": session_id,
            "provider_thread_id": session_id,
            "provider_turn_id": turn_id,
            "subtype": _string(getattr(message, "subtype", None)),
            "result": _string(getattr(message, "result", None)),
            "stop_reason": _string(getattr(message, "stop_reason", None)),
            "duration_ms": getattr(message, "duration_ms", None),
            "duration_api_ms": getattr(message, "duration_api_ms", None),
            "num_turns": getattr(message, "num_turns", None),
            "total_cost_usd": getattr(message, "total_cost_usd", None),
            "usage": _jsonable(getattr(message, "usage", None)),
            "model_usage": _jsonable(getattr(message, "model_usage", None)),
        }
        if is_error and not payload.get("result"):
            payload["error"] = payload.get("subtype") or "claude_code_error"
        return self._envelope(
            event_type,
            request,
            payload,
            raw_event=raw,
            provider_session_id=session_id,
        )

    def _map_stream_event(
        self,
        request: JsonDict,
        message: Any,
        raw: JsonDict,
    ) -> ProviderEnvelope | None:
        event = getattr(message, "event", None)
        if not isinstance(event, dict):
            return None
        delta = event.get("delta") if isinstance(event.get("delta"), dict) else {}
        text = delta.get("text") or delta.get("thinking")
        if not isinstance(text, str) or not text:
            return None
        event_type = "reasoning.delta" if delta.get("thinking") else "assistant.delta"
        return self._envelope(
            event_type,
            request,
            {"text": text, "provider": self.name},
            raw_event=raw,
            provider_event_id=_string(getattr(message, "uuid", None)),
            provider_session_id=_string(getattr(message, "session_id", None)),
        )

    def _turn_failed(
        self,
        request: JsonDict,
        *,
        code: str,
        message: str,
        raw_event: JsonDict | None = None,
    ) -> ProviderEnvelope:
        return self._envelope(
            "turn.failed",
            request,
            {
                "provider": self.name,
                "status": "failed",
                "error": code,
                "message": message,
            },
            raw_event=raw_event,
        )

    def _envelope(
        self,
        event_type: str,
        request: JsonDict,
        payload: JsonDict,
        *,
        raw_event: JsonDict | None = None,
        provider_event_id: str | None = None,
        provider_session_id: str | None = None,
    ) -> ProviderEnvelope:
        provider_turn_id = _string(payload.get("provider_turn_id")) or _string(
            _payload_value(request, "turn_id")
        )
        provider_session_id = (
            provider_session_id
            or _string(payload.get("provider_session_id"))
            or _string(_payload_value(request, "provider_session_id"))
        )
        provider_thread_id = (
            _string(payload.get("provider_thread_id"))
            or provider_session_id
            or _string(_payload_value(request, "provider_thread_id"))
            or _string(_payload_value(request, "app_server_thread_id"))
            or _string(_payload_value(request, "thread_id"))
        )
        enriched = {
            **payload,
            "provider": payload.get("provider") or self.name,
            "provider_turn_id": provider_turn_id,
            "provider_thread_id": provider_thread_id,
            "provider_session_id": provider_session_id,
        }
        return ProviderEnvelope(
            type=event_type,
            payload=enriched,
            raw_event=raw_event,
            provider_event_id=provider_event_id
            or _string(payload.get("provider_event_id")),
            provider_thread_id=provider_thread_id,
            provider_turn_id=provider_turn_id,
            provider_session_id=provider_session_id,
        )

    def _cwd_for_request(self, request: JsonDict) -> Path:
        explicit_cwd = _string(_payload_value(request, "cwd"))
        if explicit_cwd:
            return Path(explicit_cwd).expanduser().resolve()
        session_id = (
            _string(_payload_value(request, "provider_session_id"))
            or _string(_payload_value(request, "provider_thread_id"))
        )
        if session_id:
            session_cwd = self._cwd_for_session(session_id)
            if session_cwd:
                return Path(session_cwd).expanduser().resolve()
        if self.default_cwd:
            return Path(self.default_cwd).expanduser().resolve()
        raise ValueError("Claude Code turns require a workspace cwd")

    def _cwd_for_session(self, session_id: str) -> str | None:
        messages = self._load_messages_from_sdk(session_id)
        if not messages:
            messages = self._load_messages_from_transcript(session_id)
        return _records_cwd(messages)

    @staticmethod
    def _error_code(err: Exception) -> str:
        name = type(err).__name__
        lowered = str(err).lower()
        if name == "CLINotFoundError":
            return "claude_code_cli_not_found"
        if "auth" in lowered or "login" in lowered:
            return "provider_auth_required"
        if name == "ClaudeAgentSdkRuntimeMissing":
            return "provider_runtime_missing"
        return "connector_error"
